version: '3.9'

services:
  lts:
    container_name: lego_teh_set
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    container_name: lts-redis-container
    command: redis-server
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
