spring:
  main:
    web-application-type: none
  application:
    name: lego_teh_set

logging:
  level:
    root: info

redis:
  host: redis
  port: 6379

profile_hub:
  host: profile-hub
  port: 8081
